// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"securevault-backend/src/models"
)

type AuthPayload struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type FileTypeEntry struct {
	MimeType string `json:"mime_type"`
	Count    int    `json:"count"`
}

type Mutation struct {
}

type Query struct {
}
