package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"fmt"
	"log"
	"securevault-backend/src/api"
	"securevault-backend/src/graphql/graph/model"
	"securevault-backend/src/graphql/middleware"
	"securevault-backend/src/models"
	"securevault-backend/src/services"
	"strings"
	"time"

	"github.com/google/uuid"
)

// FilesByType is the resolver for the files_by_type field.
func (r *adminStatsResponseResolver) FilesByType(ctx context.Context, obj *api.AdminStatsResponse) ([]*model.FileTypeEntry, error) {
	// Convert map to slice of FileTypeEntry
	entries := make([]*model.FileTypeEntry, 0, len(obj.FilesByType))
	for mimeType, count := range obj.FilesByType {
		entries = append(entries, &model.FileTypeEntry{
			MimeType: mimeType,
			Count:    count,
		})
	}

	return entries, nil
}

// ShareLink is the resolver for the share_link field.
func (r *fileResolver) ShareLink(ctx context.Context, obj *models.File) (*models.ShareLink, error) {
	// Only return share link if file is public
	if !obj.IsPublic {
		return nil, nil
	}

	// Get share link from file service
	shareLink, err := r.FileService.GetShareLinkByFileID(obj.ID)
	if err != nil {
		// If no share link exists, return nil (not an error)
		return nil, nil
	}

	return shareLink, nil
}

// Files is the resolver for the files field.
func (r *fileListResponseResolver) Files(ctx context.Context, obj *api.FileListResponse) ([]*models.File, error) {
	// Convert API response back to models
	files := make([]*models.File, len(obj.Files))
	for i, apiFile := range obj.Files {
		fileID, err := uuid.Parse(apiFile.ID)
		if err != nil {
			return nil, fmt.Errorf("invalid file ID: %w", err)
		}

		createdAt, err := time.Parse("2006-01-02T15:04:05Z", apiFile.CreatedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid created_at time: %w", err)
		}

		updatedAt, err := time.Parse("2006-01-02T15:04:05Z", apiFile.UpdatedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid updated_at time: %w", err)
		}

		// Parse folder ID if present
		var folderID *uuid.UUID
		if apiFile.FolderID != nil {
			parsedFolderID, err := uuid.Parse(*apiFile.FolderID)
			if err != nil {
				return nil, fmt.Errorf("invalid folder ID: %w", err)
			}
			folderID = &parsedFolderID
		}

		files[i] = &models.File{
			ID:               fileID,
			OriginalFilename: apiFile.OriginalFilename,
			MimeType:         apiFile.MimeType,
			SizeBytes:        apiFile.SizeBytes,
			IsPublic:         apiFile.IsPublic,
			DownloadCount:    int(apiFile.DownloadCount),
			Tags:             apiFile.Tags,
			FolderID:         folderID,
			CreatedAt:        createdAt,
			UpdatedAt:        updatedAt,
		}
	}

	return files, nil
}

// ShareLink is the resolver for the share_link field.
func (r *folderResolver) ShareLink(ctx context.Context, obj *models.Folder) (*models.ShareLink, error) {
	// Get share link from folder service if it exists
	shareLink, err := r.FolderService.GetShareLinkByFolderID(obj.ID)
	if err != nil {
		// If no share link exists, return nil (not an error)
		if err == services.ErrShareLinkNotFound {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to get share link: %w", err)
	}

	return shareLink, nil
}

// Folders is the resolver for the folders field.
func (r *folderChildrenResponseResolver) Folders(ctx context.Context, obj *api.FolderChildrenResponse) ([]*models.Folder, error) {
	// Convert api.FolderResponse to models.Folder
	folders := make([]*models.Folder, len(obj.Folders))
	for i, apiFolder := range obj.Folders {
		// Parse UUID from string
		folderID, err := uuid.Parse(apiFolder.ID)
		if err != nil {
			return nil, fmt.Errorf("invalid folder ID: %w", err)
		}

		// Parse parent ID if present
		var parentID *uuid.UUID
		if apiFolder.ParentID != nil {
			parsedParentID, err := uuid.Parse(*apiFolder.ParentID)
			if err != nil {
				return nil, fmt.Errorf("invalid parent ID: %w", err)
			}
			parentID = &parsedParentID
		}

		// Parse timestamps
		createdAt, err := time.Parse(time.RFC3339, apiFolder.CreatedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid created_at timestamp: %w", err)
		}

		updatedAt, err := time.Parse(time.RFC3339, apiFolder.UpdatedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid updated_at timestamp: %w", err)
		}

		folders[i] = &models.Folder{
			ID:        folderID,
			Name:      apiFolder.Name,
			ParentID:  parentID,
			CreatedAt: createdAt,
			UpdatedAt: updatedAt,
		}
	}
	return folders, nil
}

// Files is the resolver for the files field.
func (r *folderChildrenResponseResolver) Files(ctx context.Context, obj *api.FolderChildrenResponse) ([]*models.File, error) {
	// Convert api.FolderFileResponse to models.File
	files := make([]*models.File, len(obj.Files))
	for i, apiFile := range obj.Files {
		// Parse UUID from string
		fileID, err := uuid.Parse(apiFile.ID)
		if err != nil {
			return nil, fmt.Errorf("invalid file ID: %w", err)
		}

		// Parse folder ID if present
		var folderID *uuid.UUID
		if apiFile.FolderID != nil {
			parsedFolderID, err := uuid.Parse(*apiFile.FolderID)
			if err != nil {
				return nil, fmt.Errorf("invalid folder ID: %w", err)
			}
			folderID = &parsedFolderID
		}

		// Parse timestamps
		createdAt, err := time.Parse(time.RFC3339, apiFile.CreatedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid created_at timestamp: %w", err)
		}

		updatedAt, err := time.Parse(time.RFC3339, apiFile.UpdatedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid updated_at timestamp: %w", err)
		}

		files[i] = &models.File{
			ID:               fileID,
			OriginalFilename: apiFile.OriginalFilename,
			MimeType:         apiFile.MimeType,
			SizeBytes:        apiFile.SizeBytes,
			FolderID:         folderID,
			IsPublic:         apiFile.IsPublic,
			DownloadCount:    apiFile.DownloadCount,
			Tags:             apiFile.Tags,
			CreatedAt:        createdAt,
			UpdatedAt:        updatedAt,
		}
	}
	return files, nil
}

// Pagination is the resolver for the pagination field.
func (r *folderChildrenResponseResolver) Pagination(ctx context.Context, obj *api.FolderChildrenResponse) (*api.FolderPaginationInfo, error) {
	// Create pagination structure with GraphQL-expected fields
	pagination := obj.FilesPagination
	pagination.TotalFolders = len(obj.Folders)         // Count of folders returned
	pagination.TotalFiles = int(pagination.TotalItems) // Total files from pagination
	pagination.HasMore = pagination.HasNext
	return &pagination, nil
}

// Folder is the resolver for the folder field.
func (r *folderDetailsResponseResolver) Folder(ctx context.Context, obj *api.FolderDetailsResponse) (*models.Folder, error) {
	// Convert api.FolderResponse to models.Folder
	folderID, err := uuid.Parse(obj.Folder.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid folder ID: %w", err)
	}

	var parentID *uuid.UUID
	if obj.Folder.ParentID != nil {
		parsedParentID, err := uuid.Parse(*obj.Folder.ParentID)
		if err != nil {
			return nil, fmt.Errorf("invalid parent ID: %w", err)
		}
		parentID = &parsedParentID
	}

	createdAt, err := time.Parse(time.RFC3339, obj.Folder.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("invalid created_at timestamp: %w", err)
	}

	updatedAt, err := time.Parse(time.RFC3339, obj.Folder.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("invalid updated_at timestamp: %w", err)
	}

	return &models.Folder{
		ID:        folderID,
		Name:      obj.Folder.Name,
		ParentID:  parentID,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}, nil
}

// Breadcrumbs is the resolver for the breadcrumbs field.
func (r *folderDetailsResponseResolver) Breadcrumbs(ctx context.Context, obj *api.FolderDetailsResponse) ([]*models.Folder, error) {
	// Convert api.FolderResponse array to models.Folder array
	breadcrumbs := make([]*models.Folder, len(obj.Breadcrumbs))
	for i, apiBreadcrumb := range obj.Breadcrumbs {
		folderID, err := uuid.Parse(apiBreadcrumb.ID)
		if err != nil {
			return nil, fmt.Errorf("invalid breadcrumb folder ID: %w", err)
		}

		var parentID *uuid.UUID
		if apiBreadcrumb.ParentID != nil {
			parsedParentID, err := uuid.Parse(*apiBreadcrumb.ParentID)
			if err != nil {
				return nil, fmt.Errorf("invalid breadcrumb parent ID: %w", err)
			}
			parentID = &parsedParentID
		}

		createdAt, err := time.Parse(time.RFC3339, apiBreadcrumb.CreatedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid breadcrumb created_at timestamp: %w", err)
		}

		updatedAt, err := time.Parse(time.RFC3339, apiBreadcrumb.UpdatedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid breadcrumb updated_at timestamp: %w", err)
		}

		breadcrumbs[i] = &models.Folder{
			ID:        folderID,
			Name:      apiBreadcrumb.Name,
			ParentID:  parentID,
			CreatedAt: createdAt,
			UpdatedAt: updatedAt,
		}
	}
	return breadcrumbs, nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	req := &services.SignUpRequest{
		Email:    email,
		Password: password,
	}

	authResponse, err := r.AuthService.SignUp(req)
	if err != nil {
		return nil, fmt.Errorf("signup failed: %w", err)
	}

	return &model.AuthPayload{
		Token: authResponse.Token,
		User:  authResponse.User,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	req := &services.LoginRequest{
		Email:    email,
		Password: password,
	}

	authResponse, err := r.AuthService.Login(req)
	if err != nil {
		return nil, fmt.Errorf("login failed: %w", err)
	}

	return &model.AuthPayload{
		Token: authResponse.Token,
		User:  authResponse.User,
	}, nil
}

// ToggleFilePublic is the resolver for the toggleFilePublic field.
func (r *mutationResolver) ToggleFilePublic(ctx context.Context, id uuid.UUID, isPublic bool) (*models.File, error) {
	// Extract user ID from context using middleware helper
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Call service to toggle file public status
	file, _, err := r.FileService.ToggleFilePublic(id, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to toggle file public status: %w", err)
	}

	return file, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, id uuid.UUID) (bool, error) {
	// Extract user ID from context using middleware helper
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Call service to delete file
	err = r.FileService.DeleteFile(id, userID)
	if err != nil {
		return false, fmt.Errorf("failed to delete file: %w", err)
	}

	return true, nil
}

// MoveFile is the resolver for the moveFile field.
func (r *mutationResolver) MoveFile(ctx context.Context, fileID uuid.UUID, folderID *uuid.UUID) (*models.File, error) {
	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Move file using file service
	err = r.FileService.MoveFile(fileID, userID, folderID)
	if err != nil {
		return nil, fmt.Errorf("failed to move file: %w", err)
	}

	// Get updated file details
	file, err := r.FileService.GetFileByID(fileID)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated file: %w", err)
	}

	return file, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, name string, parentID *uuid.UUID) (*models.Folder, error) {
	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Create folder using folder service
	folder, err := r.FolderService.CreateFolder(userID, name, parentID)
	if err != nil {
		return nil, fmt.Errorf("failed to create folder: %w", err)
	}

	return folder, nil
}

// UpdateFolder is the resolver for the updateFolder field.
func (r *mutationResolver) UpdateFolder(ctx context.Context, id uuid.UUID, name *string) (*models.Folder, error) {
	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Validate name parameter
	if name == nil || *name == "" {
		return nil, fmt.Errorf("folder name is required")
	}

	// Update folder using folder service
	folder, err := r.FolderService.RenameFolder(userID, id, *name)
	if err != nil {
		return nil, fmt.Errorf("failed to update folder: %w", err)
	}

	return folder, nil
}

// MoveFolder is the resolver for the moveFolder field.
func (r *mutationResolver) MoveFolder(ctx context.Context, id uuid.UUID, parentID *uuid.UUID) (*models.Folder, error) {
	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Move folder using folder service
	folder, err := r.FolderService.MoveFolder(userID, id, parentID)
	if err != nil {
		return nil, fmt.Errorf("failed to move folder: %w", err)
	}

	return folder, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, id uuid.UUID, recursive *bool) (bool, error) {
	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Default recursive to true
	recursiveDelete := true
	if recursive != nil {
		recursiveDelete = *recursive
	}

	// Delete folder using folder service
	err = r.FolderService.DeleteFolder(userID, id, recursiveDelete)
	if err != nil {
		return false, fmt.Errorf("failed to delete folder: %w", err)
	}

	return true, nil
}

// CreateFolderShareLink is the resolver for the createFolderShareLink field.
func (r *mutationResolver) CreateFolderShareLink(ctx context.Context, id uuid.UUID) (*models.ShareLink, error) {
	// Get user ID from context (authentication middleware should have set this)
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Use the folder service to create share link (same as REST API)
	_, shareLink, err := r.FolderService.SetFolderPublic(id, true, userID)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			return nil, fmt.Errorf("folder not found")
		}
		return nil, fmt.Errorf("failed to create share link: %w", err)
	}

	// Return the model directly (same as other GraphQL mutations)
	return shareLink, nil
}

// DeleteFolderShareLink is the resolver for the deleteFolderShareLink field.
func (r *mutationResolver) DeleteFolderShareLink(ctx context.Context, id uuid.UUID) (bool, error) {
	// Get user ID from context (authentication middleware should have set this)
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Use the folder service to disable share link (same as REST API)
	_, _, err = r.FolderService.SetFolderPublic(id, false, userID)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			return false, fmt.Errorf("folder not found")
		}
		return false, fmt.Errorf("failed to delete share link: %w", err)
	}

	return true, nil
}

// TrashFile is the resolver for the trashFile field.
func (r *mutationResolver) TrashFile(ctx context.Context, id uuid.UUID) (bool, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	err = r.FileService.TrashFile(id, userID)
	if err != nil {
		return false, fmt.Errorf("failed to trash file: %w", err)
	}

	return true, nil
}

// TrashFolder is the resolver for the trashFolder field.
func (r *mutationResolver) TrashFolder(ctx context.Context, id uuid.UUID, recursive *bool) (bool, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Default recursive to true
	rec := true
	if recursive != nil {
		rec = *recursive
	}

	err = r.FolderService.TrashFolder(id, userID, rec)
	if err != nil {
		return false, fmt.Errorf("failed to trash folder: %w", err)
	}

	return true, nil
}

// RestoreFile is the resolver for the restoreFile field.
func (r *mutationResolver) RestoreFile(ctx context.Context, id uuid.UUID) (*models.File, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	file, err := r.FileService.RestoreFile(id, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to restore file: %w", err)
	}

	return file, nil
}

// RestoreFolder is the resolver for the restoreFolder field.
func (r *mutationResolver) RestoreFolder(ctx context.Context, id uuid.UUID) (*models.Folder, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	folder, err := r.FolderService.RestoreFolder(id, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to restore folder: %w", err)
	}

	return folder, nil
}

// PermanentDeleteFile is the resolver for the permanentDeleteFile field.
func (r *mutationResolver) PermanentDeleteFile(ctx context.Context, id uuid.UUID) (bool, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	err = r.FileService.PermanentDeleteFile(id, userID)
	if err != nil {
		return false, fmt.Errorf("failed to permanently delete file: %w", err)
	}

	return true, nil
}

// PermanentDeleteFolder is the resolver for the permanentDeleteFolder field.
func (r *mutationResolver) PermanentDeleteFolder(ctx context.Context, id uuid.UUID) (bool, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	err = r.FolderService.PermanentDeleteFolder(id, userID)
	if err != nil {
		return false, fmt.Errorf("failed to permanently delete folder: %w", err)
	}

	return true, nil
}

// EmptyTrash is the resolver for the emptyTrash field.
func (r *mutationResolver) EmptyTrash(ctx context.Context) (bool, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Empty trashed files
	err = r.FileService.EmptyTrashFiles(userID)
	if err != nil {
		return false, fmt.Errorf("failed to empty trash files: %w", err)
	}

	// Empty trashed folders
	err = r.FolderService.EmptyTrashFolders(userID)
	if err != nil {
		return false, fmt.Errorf("failed to empty trash folders: %w", err)
	}

	return true, nil
}

// UpdateFileTags is the resolver for the updateFileTags field.
func (r *mutationResolver) UpdateFileTags(ctx context.Context, fileID uuid.UUID, tags []string) (*models.File, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	file, err := r.FileService.UpdateFileTags(fileID, userID, tags)
	if err != nil {
		return nil, fmt.Errorf("failed to update file tags: %w", err)
	}

	return file, nil
}

// GenerateAiTags is the resolver for the generateAiTags field.
func (r *mutationResolver) GenerateAiTags(ctx context.Context, fileID uuid.UUID) (*model.AiTagJob, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if r.AiTagService == nil || !r.AiTagService.IsEnabled() {
		return nil, fmt.Errorf("AI tag generation is not enabled")
	}

	services.TryRunBackground(func() { r.AiTagService.GenerateTagsForFile(fileID, userID) })

	// Return a pending job status
	return &model.AiTagJob{
		FileID:           fileID,
		Status:           "processing",
		SuggestedTags:    []string{},
		ConfidenceScores: []float64{},
		AiDescription:    "",
	}, nil
}

// GenerateAiDescription is the resolver for the generateAiDescription field.
func (r *mutationResolver) GenerateAiDescription(ctx context.Context, fileID uuid.UUID) (*model.AiDescriptionResult, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if r.AiTagService == nil || !r.AiTagService.IsEnabled() {
		return nil, fmt.Errorf("AI service is not enabled")
	}

	result, err := r.AiTagService.GenerateDescription(fileID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to generate AI description: %w", err)
	}

	return &model.AiDescriptionResult{
		FileID:      result.FileID,
		Description: result.Description,
		Status:      result.Status,
	}, nil
}

// BulkGenerateAiTags is the resolver for the bulkGenerateAiTags field.
func (r *mutationResolver) BulkGenerateAiTags(ctx context.Context, fileIds []uuid.UUID) (*model.BulkAiTagResult, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if r.AiTagService == nil || !r.AiTagService.IsEnabled() {
		return nil, fmt.Errorf("AI service is not enabled")
	}

	result, err := r.AiTagService.BulkGenerateTags(fileIds, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to bulk generate AI tags: %w", err)
	}

	return &model.BulkAiTagResult{
		QueuedCount:  result.QueuedCount,
		SkippedCount: result.SkippedCount,
		Status:       result.Status,
		Message:      result.Message,
	}, nil
}

// AdminDeleteFile is the resolver for the adminDeleteFile field.
func (r *mutationResolver) AdminDeleteFile(ctx context.Context, id uuid.UUID) (bool, error) {
	// Extract user ID from context and verify admin role
	_, err := middleware.RequireAdmin(ctx)
	if err != nil {
		return false, err
	}

	// Call service to delete file (admin can delete any file)
	err = r.FileService.DeleteFileAsAdmin(id)
	if err != nil {
		return false, fmt.Errorf("failed to delete file: %w", err)
	}

	return true, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello World! GraphQL server is running.", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	// Extract user ID from context using middleware helper
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Get user from auth service
	user, err := r.AuthService.GetUserByID(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return user, nil
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, filename *string, mimeType *string, folderID *uuid.UUID, tags *string, page *int, pageSize *int) (*api.FileListResponse, error) {
	// Extract user ID from context using middleware helper
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Build request with defaults
	req := services.FileListRequest{
		OwnerID:  &userID,
		Page:     1,
		PageSize: 20,
	}

	if page != nil && *page > 0 {
		req.Page = *page
	}
	if pageSize != nil && *pageSize > 0 {
		req.PageSize = *pageSize
	}
	if filename != nil {
		req.Search = *filename
	}
	if mimeType != nil {
		req.MimeTypes = []string{*mimeType}
	}
	if folderID != nil {
		// FolderID is now a UUID, so use it directly
		req.FolderID = folderID
	}
	if tags != nil && *tags != "" {
		// Split comma-separated tags and trim whitespace
		tagList := strings.Split(*tags, ",")
		for i, tag := range tagList {
			tagList[i] = strings.TrimSpace(tag)
		}
		req.Tags = tagList
	}

	// Call service
	response, err := r.FileService.ListFilesEnhanced(req)
	if err != nil {
		return nil, fmt.Errorf("failed to list files: %w", err)
	}

	// Convert to GraphQL response format
	apiResponse := &api.FileListResponse{
		Files:    make([]api.FileResponse, len(response.Files)),
		Page:     response.Pagination.Page,
		PageSize: response.Pagination.PageSize,
		Total:    response.Pagination.TotalItems,
	}

	// Convert models to API response format for GraphQL
	for i, file := range response.Files {
		var folderIDStr *string
		if file.FolderID != nil {
			str := file.FolderID.String()
			folderIDStr = &str
		}

		apiResponse.Files[i] = api.FileResponse{
			ID:               file.ID.String(),
			OriginalFilename: file.OriginalFilename,
			MimeType:         file.MimeType,
			SizeBytes:        file.SizeBytes,
			IsPublic:         file.IsPublic,
			DownloadCount:    int64(file.DownloadCount),
			Tags:             file.Tags,
			FolderID:         folderIDStr,
			CreatedAt:        file.CreatedAt.Format("2006-01-02T15:04:05Z"),
			UpdatedAt:        file.UpdatedAt.Format("2006-01-02T15:04:05Z"),
		}

		// TODO: Add share link resolution for public files
		// Share links need to be fetched separately from FileService
	}

	return apiResponse, nil
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context, parentID *uuid.UUID) (*api.FolderChildrenResponse, error) {
	log.Printf("[GQL-FOLDERS] Starting folders query - parent_id: %v", parentID)

	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		log.Printf("[GQL-FOLDERS] Auth failed: %v", err)
		return nil, err
	}
	log.Printf("[GQL-FOLDERS] Authenticated user: %s", userID)

	// Get folder children using folder service
	log.Printf("[GQL-FOLDERS] Calling FolderService.ListChildren(userID=%s, parentID=%v, page=1, pageSize=20)", userID, parentID)
	children, err := r.FolderService.ListChildren(userID, parentID, 1, 20)
	if err != nil {
		log.Printf("[GQL-FOLDERS] FolderService.ListChildren failed: %v", err)
		return nil, fmt.Errorf("failed to get folders: %w", err)
	}
	log.Printf("[GQL-FOLDERS] FolderService.ListChildren success - folders: %d, files: %d", len(children.Folders), len(children.Files))

	// Convert service response to API response format
	response := &api.FolderChildrenResponse{
		Folders: make([]api.FolderResponse, len(children.Folders)),
		Files:   make([]api.FolderFileResponse, len(children.Files)),
		FilesPagination: api.FolderPaginationInfo{
			Page:        children.FilesPagination.Page,
			PageSize:    children.FilesPagination.PageSize,
			TotalItems:  children.FilesPagination.TotalItems,
			TotalPages:  children.FilesPagination.TotalPages,
			HasNext:     children.FilesPagination.HasNext,
			HasPrevious: children.FilesPagination.HasPrevious,
		},
	}

	// Convert folders
	for i, folder := range children.Folders {
		response.Folders[i] = api.FolderResponse{
			ID:   folder.ID.String(),
			Name: folder.Name,
			ParentID: func() *string {
				if folder.ParentID != nil {
					s := folder.ParentID.String()
					return &s
				}
				return nil
			}(),
			CreatedAt: folder.CreatedAt.Format(time.RFC3339),
			UpdatedAt: folder.UpdatedAt.Format(time.RFC3339),
		}
	}

	// Convert files
	for i, file := range children.Files {
		response.Files[i] = api.FolderFileResponse{
			ID:               file.ID.String(),
			OriginalFilename: file.OriginalFilename,
			MimeType:         file.MimeType,
			SizeBytes:        file.SizeBytes,
			CreatedAt:        file.CreatedAt.Format(time.RFC3339),
			UpdatedAt:        file.UpdatedAt.Format(time.RFC3339),
			IsPublic:         file.IsPublic,
			DownloadCount:    int(file.DownloadCount),
			Tags:             []string{}, // TODO: Add tags support if available
			FolderID: func() *string {
				if file.FolderID != nil {
					s := file.FolderID.String()
					return &s
				}
				return nil
			}(),
		}
	}

	log.Printf("[GQL-FOLDERS] Response ready - returning %d folders and %d files", len(response.Folders), len(response.Files))
	return response, nil
}

// FoldersOnly is the resolver for the foldersOnly field.
func (r *queryResolver) FoldersOnly(ctx context.Context, parentID *uuid.UUID) ([]*models.Folder, error) {
	log.Printf("[GQL-FOLDERSONLY] Starting foldersOnly query - parent_id: %v", parentID)

	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		log.Printf("[GQL-FOLDERSONLY] Auth failed: %v", err)
		return nil, err
	}
	log.Printf("[GQL-FOLDERSONLY] Authenticated user: %s", userID)

	// Get folders using the simple folder service method
	log.Printf("[GQL-FOLDERSONLY] Calling FolderService.ListFoldersOnly(userID=%s, parentID=%v)", userID, parentID)
	folders, err := r.FolderService.ListFoldersOnly(userID, parentID)
	if err != nil {
		log.Printf("[GQL-FOLDERSONLY] FolderService.ListFoldersOnly failed: %v", err)
		return nil, fmt.Errorf("failed to get folders: %w", err)
	}

	log.Printf("[GQL-FOLDERSONLY] FolderService.ListFoldersOnly success - returning %d folders", len(folders))
	return folders, nil
}

// AllFolders is the resolver for the allFolders field.
func (r *queryResolver) AllFolders(ctx context.Context) ([]*models.Folder, error) {
	log.Printf("[GQL-ALLFOLDERS] Starting allFolders query")

	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		log.Printf("[GQL-ALLFOLDERS] Auth failed: %v", err)
		return nil, err
	}
	log.Printf("[GQL-ALLFOLDERS] Authenticated user: %s", userID)

	// Get all folders for the user
	log.Printf("[GQL-ALLFOLDERS] Calling FolderService.GetAllFolders(userID=%s)", userID)
	folders, err := r.FolderService.GetAllFolders(userID)
	if err != nil {
		log.Printf("[GQL-ALLFOLDERS] FolderService.GetAllFolders failed: %v", err)
		return nil, fmt.Errorf("failed to get all folders: %w", err)
	}

	log.Printf("[GQL-ALLFOLDERS] FolderService.GetAllFolders success - returning %d folders", len(folders))
	return folders, nil
}

// Folder is the resolver for the folder field.
func (r *queryResolver) Folder(ctx context.Context, id uuid.UUID) (*api.FolderDetailsResponse, error) {
	// Get authenticated user
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Get folder details
	folder, err := r.FolderService.GetFolderByID(userID, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get folder: %w", err)
	}

	// Get breadcrumbs
	breadcrumbs, err := r.FolderService.GetBreadcrumbs(userID, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get breadcrumbs: %w", err)
	}

	// Convert to API response format
	response := &api.FolderDetailsResponse{
		Folder: api.FolderResponse{
			ID:   folder.ID.String(),
			Name: folder.Name,
			ParentID: func() *string {
				if folder.ParentID != nil {
					s := folder.ParentID.String()
					return &s
				}
				return nil
			}(),
			CreatedAt: folder.CreatedAt.Format(time.RFC3339),
			UpdatedAt: folder.UpdatedAt.Format(time.RFC3339),
		},
		Breadcrumbs: make([]api.FolderResponse, len(breadcrumbs)),
	}

	// Convert breadcrumbs
	for i, bc := range breadcrumbs {
		response.Breadcrumbs[i] = api.FolderResponse{
			ID:   bc.ID.String(),
			Name: bc.Name,
			ParentID: func() *string {
				if bc.ParentID != nil {
					s := bc.ParentID.String()
					return &s
				}
				return nil
			}(),
			CreatedAt: bc.CreatedAt.Format(time.RFC3339),
			UpdatedAt: bc.UpdatedAt.Format(time.RFC3339),
		}
	}

	return response, nil
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, id uuid.UUID) (*models.File, error) {
	// Extract user ID from context using middleware helper
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Call service to get file with authorization check
	file, err := r.FileService.GetFileForDownload(id, &userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get file: %w", err)
	}

	return file, nil
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context, from *string, to *string, groupBy *string) (*api.StatsResponse, error) {
	log.Printf("[GQL-STATS] Starting stats query - from: %v, to: %v, groupBy: %v", from, to, groupBy)

	// Extract user ID from context using middleware helper
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		log.Printf("[GQL-STATS] Auth failed: %v", err)
		return nil, err
	}
	log.Printf("[GQL-STATS] Authenticated user: %s", userID)

	// Call service to get user stats
	log.Printf("[GQL-STATS] Calling StatsService.GetUserStats(userID=%s)", userID)
	userStats, err := r.StatsService.GetUserStats(userID)
	if err != nil {
		log.Printf("[GQL-STATS] StatsService.GetUserStats failed: %v", err)
		return nil, fmt.Errorf("failed to get user stats: %w", err)
	}
	log.Printf("[GQL-STATS] StatsService.GetUserStats success - files: %d, size: %d bytes", userStats.TotalFiles, userStats.TotalSizeBytes)

	// For now, return empty data for files by type and upload history
	// TODO: Implement these using StatsService methods
	filesByType := make(map[string]int)
	uploadHistory := make([]api.UploadHistoryEntry, 0)
	// if uploadHistory == nil {
	// 	uploadHistory = []api.UploadHistoryEntry{}
	// }

	// Convert to API response format
	response := &api.StatsResponse{
		TotalFiles:          userStats.TotalFiles,
		TotalSizeBytes:      userStats.TotalSizeBytes,
		QuotaBytes:          userStats.StorageQuotaBytes,
		QuotaUsedBytes:      userStats.TotalSizeBytes,
		QuotaAvailableBytes: userStats.StorageQuotaBytes - userStats.TotalSizeBytes,
		FilesByType:         filesByType,
		UploadHistory:       uploadHistory,
	}

	log.Printf("[GQL-STATS] Response ready - totalFiles: %d, totalSizeBytes: %d, quotaBytes: %d",
		response.TotalFiles, response.TotalSizeBytes, response.QuotaBytes)
	return response, nil
}

// PublicFile is the resolver for the publicFile field.
func (r *queryResolver) PublicFile(ctx context.Context, token string) (*models.File, error) {
	// Call service to get public file by share token (no auth required)
	file, err := r.FileService.GetFileByShareToken(token)
	if err != nil {
		return nil, fmt.Errorf("failed to get public file: %w", err)
	}

	return file, nil
}

// PublicFolder is the resolver for the publicFolder field.
func (r *queryResolver) PublicFolder(ctx context.Context, token string, page *int, pageSize *int) (*api.FolderChildrenResponse, error) {
	// Set default page and page_size if not provided
	pageNum := 1
	if page != nil {
		pageNum = *page
	}

	pageSizeNum := 20
	if pageSize != nil {
		pageSizeNum = *pageSize
	}

	// Validate token format
	if token == "" {
		return nil, fmt.Errorf("invalid share token")
	}

	// Get folder by public share token (no auth required)
	folder, err := r.FolderService.GetFolderByShareToken(token)
	if err != nil {
		if err.Error() == "share link not found" {
			return nil, fmt.Errorf("public folder link not found")
		} else if err.Error() == "share link has expired" {
			return nil, fmt.Errorf("public folder link has expired")
		} else if err.Error() == "invalid share token format" {
			return nil, fmt.Errorf("invalid share token format")
		} else {
			return nil, fmt.Errorf("failed to retrieve folder: %w", err)
		}
	}

	// Get folder contents using the folder's owner ID and folder ID
	folderID := &folder.ID
	children, err := r.FolderService.ListChildren(folder.OwnerID, folderID, pageNum, pageSizeNum)
	if err != nil {
		return nil, fmt.Errorf("failed to list folder contents: %w", err)
	}

	// Convert service response to API response format
	response := &api.FolderChildrenResponse{
		Folders: make([]api.FolderResponse, len(children.Folders)),
		Files:   make([]api.FolderFileResponse, len(children.Files)),
		FilesPagination: api.FolderPaginationInfo{
			Page:        children.FilesPagination.Page,
			PageSize:    children.FilesPagination.PageSize,
			TotalItems:  children.FilesPagination.TotalItems,
			TotalPages:  children.FilesPagination.TotalPages,
			HasNext:     children.FilesPagination.HasNext,
			HasPrevious: children.FilesPagination.HasPrevious,
		},
	}

	// Convert folders
	for i, folder := range children.Folders {
		response.Folders[i] = api.FolderResponse{
			ID:   folder.ID.String(),
			Name: folder.Name,
			ParentID: func() *string {
				if folder.ParentID != nil {
					s := folder.ParentID.String()
					return &s
				}
				return nil
			}(),
			CreatedAt: folder.CreatedAt.Format(time.RFC3339),
			UpdatedAt: folder.UpdatedAt.Format(time.RFC3339),
		}
	}

	// Convert files
	for i, file := range children.Files {
		response.Files[i] = api.FolderFileResponse{
			ID:               file.ID.String(),
			OriginalFilename: file.OriginalFilename,
			MimeType:         file.MimeType,
			SizeBytes:        file.SizeBytes,
			CreatedAt:        file.CreatedAt.Format(time.RFC3339),
			UpdatedAt:        file.UpdatedAt.Format(time.RFC3339),
			IsPublic:         file.IsPublic,
			DownloadCount:    int(file.DownloadCount),
			Tags:             []string{}, // TODO: Add tags support if available
			FolderID: func() *string {
				if file.FolderID != nil {
					s := file.FolderID.String()
					return &s
				}
				return nil
			}(),
		}
	}

	return response, nil
}

// Trash is the resolver for the trash field.
func (r *queryResolver) Trash(ctx context.Context, page *int, pageSize *int) (*model.TrashResponse, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Set defaults
	p := 1
	ps := 20
	if page != nil && *page > 0 {
		p = *page
	}
	if pageSize != nil && *pageSize > 0 {
		ps = *pageSize
	}

	// Get trashed files
	files, totalFiles, err := r.FileService.GetTrashedFiles(userID, p, ps)
	if err != nil {
		return nil, fmt.Errorf("failed to get trashed files: %w", err)
	}

	// Get trashed folders
	folders, totalFolders, err := r.FolderService.GetTrashedFolders(userID, p, ps)
	if err != nil {
		return nil, fmt.Errorf("failed to get trashed folders: %w", err)
	}

	return &model.TrashResponse{
		Files:    files,
		Folders:  folders,
		Page:     p,
		PageSize: ps,
		Total:    totalFiles + totalFolders,
	}, nil
}

// AdminFiles is the resolver for the adminFiles field.
func (r *queryResolver) AdminFiles(ctx context.Context, userID *uuid.UUID, userEmail *string, filename *string, mimeType *string, tags *string, page *int, pageSize *int) (*api.AdminFilesResponse, error) {
	// Extract current user ID from context and verify admin role
	_, err := middleware.RequireAdmin(ctx)
	if err != nil {
		return nil, err
	}

	// Build request (simplified - TODO: implement full admin filtering)
	req := services.FileListRequest{
		Page:     1,
		PageSize: 20,
	}

	if page != nil && *page > 0 {
		req.Page = *page
	}
	if pageSize != nil && *pageSize > 0 {
		req.PageSize = *pageSize
	}
	if userID != nil {
		req.OwnerID = userID
	}
	if filename != nil {
		req.Search = *filename
	}
	if mimeType != nil {
		req.MimeTypes = []string{*mimeType}
	}

	// Call service (TODO: Create proper admin list method)
	response, err := r.FileService.ListFilesEnhanced(req)
	if err != nil {
		return nil, fmt.Errorf("failed to list admin files: %w", err)
	}

	// Convert to admin response format (simplified)
	adminFiles := make([]api.AdminFileEntry, len(response.Files))
	for i, file := range response.Files {
		adminFiles[i] = api.AdminFileEntry{
			ID:            file.ID,
			Filename:      file.OriginalFilename,
			Size:          file.SizeBytes,
			MimeType:      file.MimeType,
			UploadDate:    file.CreatedAt,
			UserID:        file.OwnerID,
			UserEmail:     "admin@example.com", // TODO: Join with user table
			IsPublic:      file.IsPublic,
			DownloadCount: int64(file.DownloadCount),
		}
	}

	adminResponse := &api.AdminFilesResponse{
		Files: adminFiles,
		Pagination: api.PaginationInfo{
			Page:       response.Pagination.Page,
			PageSize:   response.Pagination.PageSize,
			Total:      int(response.Pagination.TotalItems),
			TotalPages: response.Pagination.TotalPages,
		},
	}

	return adminResponse, nil
}

// AdminStats is the resolver for the adminStats field.
func (r *queryResolver) AdminStats(ctx context.Context) (*api.AdminStatsResponse, error) {
	// Extract current user ID from context and verify admin role
	_, err := middleware.RequireAdmin(ctx)
	if err != nil {
		return nil, err
	}

	// Call service to get system stats
	systemStats, err := r.StatsService.GetSystemStats()
	if err != nil {
		return nil, fmt.Errorf("failed to get admin stats: %w", err)
	}

	// Convert to admin response format (simplified)
	adminResponse := &api.AdminStatsResponse{
		TotalUsers:              systemStats.TotalUsers,
		TotalFiles:              systemStats.TotalFiles,
		TotalSizeBytes:          systemStats.TotalSizeBytes,
		TotalQuotaBytes:         0,                         // TODO: Calculate total quota from users
		QuotaUtilizationPercent: 0.0,                       // TODO: Calculate quota utilization
		FilesByType:             make(map[string]int),      // TODO: Implement file type breakdown
		UsersByRegistrationDate: []api.RegistrationEntry{}, // TODO: Implement registration history
		StorageByUser:           []api.UserStorageEntry{},  // TODO: Implement user storage breakdown
		MostActiveUsers:         []api.ActiveUserEntry{},   // TODO: Implement active users
	}

	return adminResponse, nil
}

// AllTags is the resolver for the allTags field.
func (r *queryResolver) AllTags(ctx context.Context) ([]*model.FileTagInfo, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	tags, err := r.FileService.GetAllTagsForUser(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get all tags: %w", err)
	}

	result := make([]*model.FileTagInfo, len(tags))
	for i, t := range tags {
		result[i] = &model.FileTagInfo{
			Name:          t.Name,
			IsAiGenerated: t.IsAiGenerated,
			Confidence:    t.Confidence,
			Count:         t.FileCount,
		}
	}

	return result, nil
}

// PopularTags is the resolver for the popularTags field.
func (r *queryResolver) PopularTags(ctx context.Context, limit *int) ([]*model.FileTagInfo, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	lim := 10
	if limit != nil && *limit > 0 {
		lim = *limit
	}

	tags, err := r.FileService.GetPopularTags(userID, lim)
	if err != nil {
		return nil, fmt.Errorf("failed to get popular tags: %w", err)
	}

	result := make([]*model.FileTagInfo, len(tags))
	for i, t := range tags {
		result[i] = &model.FileTagInfo{
			Name:          t.Name,
			IsAiGenerated: t.IsAiGenerated,
			Confidence:    t.Confidence,
			Count:         t.FileCount,
		}
	}

	return result, nil
}

// SearchSuggestions is the resolver for the searchSuggestions field.
func (r *queryResolver) SearchSuggestions(ctx context.Context, query string, limit *int) ([]*model.SearchSuggestion, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	lim := 10
	if limit != nil && *limit > 0 {
		lim = *limit
	}

	suggestions, err := r.FileService.SearchSuggestions(userID, query, lim)
	if err != nil {
		return nil, fmt.Errorf("failed to get search suggestions: %w", err)
	}

	result := make([]*model.SearchSuggestion, len(suggestions))
	for i, s := range suggestions {
		result[i] = &model.SearchSuggestion{
			Type:  s.Type,
			Value: s.Value,
			ID:    s.ID,
			Count: s.Count,
		}
	}

	return result, nil
}

// AiTags is the resolver for the aiTags field.
func (r *queryResolver) AiTags(ctx context.Context, fileID uuid.UUID) (*model.AiTagJob, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if r.AiTagService == nil {
		return nil, fmt.Errorf("AI tag service not available")
	}

	job, err := r.AiTagService.GetAiTagJob(fileID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get AI tags: %w", err)
	}

	if job == nil {
		return nil, nil // No job exists yet
	}

	return &model.AiTagJob{
		ID:               job.ID,
		FileID:           job.FileID,
		Status:           job.Status,
		SuggestedTags:    job.SuggestedTags,
		ConfidenceScores: job.ConfidenceScores,
		AiDescription:    job.AiDescription,
		SuggestedFolder:  &job.SuggestedFolder,
		ErrorMessage:     job.ErrorMessage,
		CreatedAt:        job.CreatedAt,
		CompletedAt:      job.CompletedAt,
	}, nil
}

// AiDescription is the resolver for the aiDescription field.
func (r *queryResolver) AiDescription(ctx context.Context, fileID uuid.UUID) (*model.AiDescriptionResult, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if r.AiTagService == nil || !r.AiTagService.IsEnabled() {
		return nil, fmt.Errorf("AI service is not enabled")
	}

	result, err := r.AiTagService.GenerateDescription(fileID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get AI description: %w", err)
	}

	return &model.AiDescriptionResult{
		FileID:      result.FileID,
		Description: result.Description,
		Status:      result.Status,
	}, nil
}

// AiAnalysis is the resolver for the aiAnalysis field.
func (r *queryResolver) AiAnalysis(ctx context.Context, fileID uuid.UUID) (*model.AiAnalysisResult, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if r.AiTagService == nil {
		return nil, fmt.Errorf("AI service not available")
	}

	job, err := r.AiTagService.GetAiTagJob(fileID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get AI analysis: %w", err)
	}

	if job == nil {
		return &model.AiAnalysisResult{
			FileID:           fileID,
			SuggestedTags:    []string{},
			ConfidenceScores: []float64{},
			Description:      "",
			Status:           "not_started",
		}, nil
	}

	return &model.AiAnalysisResult{
		FileID:           job.FileID,
		SuggestedTags:    job.SuggestedTags,
		ConfidenceScores: job.ConfidenceScores,
		Description:      job.AiDescription,
		SuggestedFolder:  &job.SuggestedFolder,
		Status:           job.Status,
	}, nil
}

// FilesByType is the resolver for the files_by_type field.
func (r *statsResponseResolver) FilesByType(ctx context.Context, obj *api.StatsResponse) ([]*model.FileTypeEntry, error) {
	// Convert map to slice of FileTypeEntry
	entries := make([]*model.FileTypeEntry, 0, len(obj.FilesByType))
	for mimeType, count := range obj.FilesByType {
		entries = append(entries, &model.FileTypeEntry{
			MimeType: mimeType,
			Count:    count,
		})
	}

	return entries, nil
}

// AdminStatsResponse returns AdminStatsResponseResolver implementation.
func (r *Resolver) AdminStatsResponse() AdminStatsResponseResolver {
	return &adminStatsResponseResolver{r}
}

// File returns FileResolver implementation.
func (r *Resolver) File() FileResolver { return &fileResolver{r} }

// FileListResponse returns FileListResponseResolver implementation.
func (r *Resolver) FileListResponse() FileListResponseResolver { return &fileListResponseResolver{r} }

// Folder returns FolderResolver implementation.
func (r *Resolver) Folder() FolderResolver { return &folderResolver{r} }

// FolderChildrenResponse returns FolderChildrenResponseResolver implementation.
func (r *Resolver) FolderChildrenResponse() FolderChildrenResponseResolver {
	return &folderChildrenResponseResolver{r}
}

// FolderDetailsResponse returns FolderDetailsResponseResolver implementation.
func (r *Resolver) FolderDetailsResponse() FolderDetailsResponseResolver {
	return &folderDetailsResponseResolver{r}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// StatsResponse returns StatsResponseResolver implementation.
func (r *Resolver) StatsResponse() StatsResponseResolver { return &statsResponseResolver{r} }

type adminStatsResponseResolver struct{ *Resolver }
type fileResolver struct{ *Resolver }
type fileListResponseResolver struct{ *Resolver }
type folderResolver struct{ *Resolver }
type folderChildrenResponseResolver struct{ *Resolver }
type folderDetailsResponseResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type statsResponseResolver struct{ *Resolver }
